services:
  postgres:
    image: postgres:13.14
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - elixir-event-manager:/var/lib/postgresql/data
    networks:
      - eem
  db_ui:
    image: adminer
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DESIGN=dracula
    networks:
      - eem
  # This is an example to run the API container. To build it, run the following command in the project roon:
  # docker build -t codeseoul/elixir-event-manager-api:0.0.1 .

  # api:
  #   image: codeseoul/elixir-event-manager-api:0.0.1
  #   ports:
  #     - 4000:4000
  #   environment:
  #     - DATABASE_HOST=postgres
  #     - DATABASE_NAME=event_manager_dev
  #     - DATABASE_USERNAME=postgres
  #     - DATABASE_PASSWORD=postgres
  #     - SECRET_KEY_BASE=secret
  #   networks:
  #     - eem

networks:
  eem:
    driver: bridge

volumes:
  elixir-event-manager: