services:
  postgres:
    image: postgres:13.14
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - elixir-event-manager:/var/lib/postgresql/data
    networks:
      - eem
  db_ui:
    image: adminer
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DESIGN=dracula
    networks:
      - eem

networks:
  eem:
    driver: bridge

volumes:
  elixir-event-manager: